conda_forge_output_validation: true

github:
  # name of the github organization
  user_or_org: GlacioHack
  # repository name, usually filled in automatically
  repo_name: xdem
  # branch name to execute on
  branch_name: main
  tooling_branch_name: main
build_with_mambabuild:
  True
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge
    - defaults
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - ["conda-forge", "main"]