{% set name = "xdem" %}
{% set version = "0.0.4" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GlacioHack/xdem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e853c54b796eed9ccd4f91811d5d7c5f19930c8a7339c3af0330f364202d4b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - proj >=7.2
    - geopandas
    - numba
    - matplotlib-base
    - opencv
    - pyproj
    - rasterio
    - scipy
    - tqdm
    - scikit-image
    - scikit-gstat
    - pytransform3d
    - geoutils

test:
  imports:
    - xdem

about:
  home: https://github.com/GlacioHack/xdem
  license: MIT
  license_file: LICENSE
  summary: Set of tools to manipulate Digital Elevation Models (DEMs)
  doc_url: https://xdem.readthedocs.io
  dev_url: https://github.com/GlacioHack/xdem

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - rhugonnet
