{% set name = "xdem" %}
{% set version = "0.0.8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GlacioHack/xdem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8cbe63574a1d47d9079efbb6c6a58516722742f0d060c4fd05a7668a79f18f7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - proj >=7.2
    - numpy
    - geopandas >=0.10.0
    - fiona
    - shapely
    - numba
    - matplotlib-base
    - opencv
    - openh264
    - pyproj
    - rasterio >=1.3.0
    - scipy
    - tqdm
    - scikit-image
    - scikit-gstat >=0.6.8
    - pytransform3d
    - geoutils == 0.0.11

test:
  imports:
    - xdem

about:
  home: https://github.com/GlacioHack/xdem
  license: MIT
  license_file: LICENSE
  summary: Analysis of digital elevation models (DEMs)
  doc_url: https://xdem.readthedocs.io
  dev_url: https://github.com/GlacioHack/xdem

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - rhugonnet
