{% set name = "xdem" %}
{% set version = "0.0.14" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GlacioHack/xdem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b10fd014230ec06e8b29d696da35affb6b8b9fac36dc8fb89b3821646fdd52d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - pip
    - proj >=7.2
    - geopandas >=0.10.0
    - fiona
    - shapely
    - numba
    - numpy
    - matplotlib-base
    - opencv
    - openh264
    - pyproj >=3.4
    - rasterio >=1.3
    - scipy
    - tqdm
    - scikit-image
    - scikit-gstat >=1.0
    - pytransform3d
    - geoutils ==0.0.11

test:
  imports:
    - xdem

about:
  home: https://github.com/GlacioHack/xdem
  license: MIT
  license_file: LICENSE
  summary: Analysis of digital elevation models (DEMs)
  doc_url: https://xdem.readthedocs.io
  dev_url: https://github.com/GlacioHack/xdem

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - rhugonnet
