{% set name = "xdem" %}
{% set version = "0.0.7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/GlacioHack/xdem/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8cbe63574a1d47d9079efbb6c6a58516722742f0d060c4fd05a7668a79f18f7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.7
    - proj >=7.2
    - numpy
    - geopandas
    - fiona
    - shapely
    - numba
    - matplotlib-base
    - opencv
    - pyproj
    - rasterio
    - scipy
    - tqdm
    - scikit-image
    - scikit-gstat >=0.6.7
    - pytransform3d
    - geoutils

test:
  imports:
    - xdem

about:
  home: https://github.com/GlacioHack/xdem
  license: MIT
  license_file: LICENSE
  summary: Set of tools to manipulate Digital Elevation Models (DEMs)
  doc_url: https://xdem.readthedocs.io
  dev_url: https://github.com/GlacioHack/xdem

extra:
  recipe-maintainers:
    - erikmannerfelt
    - adehecq
    - rhugonnet
